"""Windows version-info generation helpers for release builds."""

from __future__ import annotations

from pathlib import Path
import re

from app.version import APP_NAME, APP_VERSION

VERSION_INFO_FILE_NAME = "version_info.txt"

def version_info_file_path(platform_build_dir: Path) -> Path:
    """Return the generated Windows version-info file path for one build."""
    return platform_build_dir / VERSION_INFO_FILE_NAME

def write_version_info_file(platform_build_dir: Path) -> Path:
    """Generate a PyInstaller Windows version-info file from the app version."""
    version_info_file = version_info_file_path(platform_build_dir)
    version_info_file.parent.mkdir(parents=True, exist_ok=True)
    version_info_file.write_text(_format_version_info_file(), encoding="utf-8")
    return version_info_file

def _format_version_info_file() -> str:
    version_tuple = _windows_version_tuple(APP_VERSION)
    return f"""# UTF-8
#
# Generated by build_release.py from app.version.
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers={version_tuple},
    prodvers={version_tuple},
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0)
  ),
  kids=[
    StringFileInfo([
      StringTable(
        '040904B0',
        [
          StringStruct('CompanyName', 'j3'),
          StringStruct('FileDescription', '{APP_NAME}'),
          StringStruct('FileVersion', '{APP_VERSION}'),
          StringStruct('InternalName', '{APP_NAME}'),
          StringStruct('OriginalFilename', '{APP_NAME}.exe'),
          StringStruct('ProductName', '{APP_NAME}'),
          StringStruct('ProductVersion', '{APP_VERSION}')
        ]
      )
    ]),
    VarFileInfo([VarStruct('Translation', [1033, 1200])])
  ]
)
"""

def _windows_version_tuple(version_text: str) -> tuple[int, int, int, int]:
    numeric_parts = []
    for part in version_text.split("."):
        match = re.match(r"(\d+)", part)
        if match is None:
            break
        numeric_parts.append(int(match.group(1)))
    while len(numeric_parts) < 4:
        numeric_parts.append(0)
    return tuple(numeric_parts[:4])

